### ISSUE TITLE
error url

### ISSUE THREAD

**Issue by brewjd** [marthoc/kuna#18]
I have 2 of the maximus smart lights, but I get this error.

 Error while executing automation automation.download_kuna_recordings. Invalid data for call_service at pos 1: invalid url for dictionary value @ data['url']

**Comment by jlax47** [comment]
double check your automation yaml, here's what mine looks like:

```
- id: '000000001'
  alias: Download Kuna Deck Door recordings
  trigger:
    platform: event
    event_type: kuna_event
    event_data:
      category: recording
      serial_number: KNP000000000000
  action:
    service: downloader.download_file
    data_template:
      url: '{{ trigger.event.data.url }}'
      subdir: DeckDoor
      filename: '{{ trigger.event.data.label }}.mp4'
```
